### ISSUE TITLE
Cannot build apk

### ISSUE THREAD

**Issue by Xawery94** [letsar/value_layout_builder#1]
When I ran ```flutter build apk``` for my flutter project I always got error.

```
Compiler message:
../../../../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/value_layout_builder-0.1.0/lib/src/sliver_value_layout_builder.dart:117:5: Error: The method 'rebuildIfNecessary' isn't defined for the class '_RenderSliverValueLayoutBuilder<T>'.
 - '_RenderSliverValueLayoutBuilder' is from 'package:value_layout_builder/src/sliver_value_layout_builder.dart' ('../../../../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/value_layout_builder-0.1.0/lib/src/sliver_value_layout_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'rebuildIfNecessary'.
    rebuildIfNecessary();
    ^^^^^^^^^^^^^^^^^^
../../../../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/value_layout_builder-0.1.0/lib/src/value_layout_builder.dart:105:5: Error: The method 'rebuildIfNecessary' isn't defined for the class '_RenderValueLayoutBuilder<T>'.
 - '_RenderValueLayoutBuilder' is from 'package:value_layout_builder/src/value_layout_builder.dart' ('../../../../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/value_layout_builder-0.1.0/lib/src/value_layout_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'rebuildIfNecessary'.
    rebuildIfNecessary();
    ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxx/Documents/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/xxx/Documents/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      12,9s
Gradle task assembleRelease failed with exit code 1

```

It's more like error with this method **rebuildIfNecessary()**
I'm running on 1.17.5 version of flutter

**Comment by letsar** [comment]
Oh I only tested it with the latest stable which is the 1.20.2. This method may have been added between. Can you try with the lastest stable Flutter version?

**Comment by Xawery94** [comment]
Yes, but for now I hardcoded version of other package in my project without this package. In near future I will try this with your package and I will let you know about process

**Comment by SebastienMelki** [comment]
Hello!
I am having this issue as well @letsar  but i cannot upgrade flutter to 1.20.2 yet because i have issues with other packages on latest flutter. For now i need to use 1.17.5, is there a way to force a specific version on a transitive dependency? So that I can fetch a version of this package that works on 1.17.5

Thanks!

**Comment by letsar** [comment]
That's the initial version of this package. What you can do for now is to fork this package and modify the code so that it would work with a previous version of Flutter. You can see RenderLayoutBuilder and RenderSliverLayoutBuilder (if I remember correctly) in Flutter source code for hints on how to modify this package.

You're using this package directly or through one of my package?

**Comment by Xawery94** [comment]
If you are using native_widgets you can use my fork with hardcoded version of packages

```
  native_widgets:
    git:
      url: https://github.com/Xawery94/native_widgets.git
```

**Comment by SebastienMelki** [comment]
> That's the initial version of this package. What you can do for now is to fork this package and modify the code so that it would work with a previous version of Flutter. You can see RenderLayoutBuilder and RenderSliverLayoutBuilder (if I remember correctly) in Flutter source code for hints on how to modify this package.
> 
> You're using this package directly or through one of my package?

I'm using through another package but can't figure out which. Is there a way to figure out which package is depending on value_layout_build through a flutter command?

**Comment by letsar** [comment]
You can see it through pub that's for sure. I don't any any Flutter command doing this but it could be helpful.

For now, to my knowledge there is only overflow_view and flutter_sticky_header. I suspect the later. If that case you can explicitly stick the version of that package to the one before.

**Comment by SebAubin** [comment]
flutter_sticky_header with version 0.4.6: https://github.com/letsar/flutter_sticky_header/releases/tag/v0.4.6

Setting the version to 0.4.5 will fix this error.

**Comment by letsar** [comment]
Yeah if you can't upgrade to 1.20 you have to set the version to 0.4.5.
