### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by John-Dormevil** [letsar/value_layout_builder#3]
Hi @letsar Thanks for your work 
We actually use your library and we want to contribute by migrating them to null safety what do you think about it ?
#2  😄

**Comment by IchordeDionysos** [comment]
@letsar you should be unblocked to support null-safety, also the Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

And @John-Dormevil made a great PR to support null safety!
Would be cool if you could take a look at the PR!

**Comment by IchordeDionysos** [comment]
The new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by zs-dima** [comment]
any updates are welcome :)

**Comment by letsar** [comment]
I left a review on the PR ;-)

**Comment by Peng-Qian** [comment]
@letsar  Cool! Please update the awesome package flutter_sticky_header to null-safty~

**Comment by letsar** [comment]
The v0.3.0 version with null-safety is out! Thanks to @John-Dormevil :-)
